apiVersion: v2
name: smarter-cni
description: smarter-cni chart for SMARTER edge devices
home: https://getsmarter.io
version: 0.0.4
appVersion: v1.34.0
kubeVersion: ">=1.16.0-0"
keywords:
  - kubernetes
  - device
  - hardware
sources:
  - https://github.com/smarter-project/smarter-cni
icon: https://github.com/smarter-project/documentation/raw/main/ARM1636_Project_Logo_ST2_RGB_V1.png
annotations:
  artifacthub.io/changes: |
    - Fix template
    - Add annotations
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Alexandre Ferreira
      email: alexandref75@gmail.com
  artifacthub.io/prerelease: "false"
  artifacthub.io/signKey: |
    fingerprint: 71EDA4E3D652DC73EB09E3A5387D298C169CF24E
    url: https://smarter-project.github.io/documentation/pgp_keys.asc
